### PR TITLE
Fix H5P module locking session while saving large content

### PR DESCRIPTION
**Pull request by katerynadegtyariova**
When a user is saving large H5P content (~2Gb) in Moodle it takes about 60 seconds to process changes. However, due to the session locking it is not possible to open another Moodle page in a new browser tab. It ends up with the error "Unable to obtain session lock".

Steps to reproduce the issue in Moodle:

Create a new course or use an existing course in Moodle.
In the course main page add a new activity.
Choose H5P Interactive Content.
Provide some description in Description section.
Inside the editor section choose Upload and upload a large H5P package.
Click "Save and Return to course".
Find the activity that has been created, click Edit -> Edit Settings.
Do not change anything, click "Save and Display". The page will be processing changes for ~90 sec. Go to next step without waiting for it to finish.
Try to open a course page in a new browser tab. It will not open, but start waiting and give the error "Unable to obtain session lock".
Profiling shows that 95% of time is spent inside h5p.classes.php: H5PExport > createExportFile > $zip->Close() call.
The solution for the session locking would be to write_close() the session before finishing zip file. It will allow other pages to use session without waiting on the file operation to finish.

The following scenarios were tested:

Save page with H5P content and try opening another page. With the patched version the new page opened instantly instead of waiting.
Open and save H5P content in two parallel uploads. This worked well too, both pages saved correctly and no unnecessary waiting happened.
Save page with H5P content and try opening the same page in a new tab. In this case the new page waited until the H5P content is saved. It seems to be the case when waiting cannot be avoided since it is trying to access the very content which is being saved.
After adding the fix all tests were conducted with Moodle logging enabled, which did not show any issues. Apache and php error logs were checked for errors as well. Everything worked as it should.

### CODE REVIEW

**Comment by brendanheywood** [comment]
My main question would be around whether this is in the right place or not. Typically you want this close to the 'top' in a place where you know that closing the session will not have side effects, ie in view.php or embed.php 

I think if we leave it where it is then it would be easy for the session to be closed prematurely as a side effect and it might cause bugs when saving to the session and it won't work. In particular we need to make sure that the code below never runs before the session is closed:

https://github.com/h5p/moodle-mod_hvp/blob/9d9e785160541095488b6184223a16b4697745f2/classes/framework.php#L321-L330

**Comment by katerynadegtyariova** [comment]
Thanks @brendanheywood 

Unfortunately, if session is not unlocked at that stage it would have to wait until the file is closed, which might take time and any other page open for the same user will end up with "Unable to obtain session lock" error.

I see only one way out of this - process the file asynchronously, which will require serious changes in the code.
Maybe there are other ways that I don't know. So, I am open for ideas.

**Comment by brendanheywood** [comment]
Can you confirm one way or another that the code below never runs before the session is closed?

https://github.com/h5p/moodle-mod_hvp/blob/9d9e785160541095488b6184223a16b4697745f2/classes/framework.php#L321-L330

**Comment by katerynadegtyariova** [comment]
I did some debugging and here are the conclusions:

the method in question `framework::messages()` is not called at all when the file content is being saved.
(https://github.com/h5p/moodle-mod_hvp/blob/9d9e785160541095488b6184223a16b4697745f2/classes/framework.php#L321-L330)

`framework::messages()` is only called when the content is loaded for viewing or editing. However, in such case the session is not closed (I updated the code to close the session only before the file storing).

**Comment by brendanheywood** [comment]
Well lets just get it live and see if we hit anything more with real life traffic

**Pull request merged**
